### ISSUE TITLE
给opencv开PR呗

### ISSUE THREAD

**Issue by DTennant** [ganler/ParallelVideoCap#1]
https://github.com/opencv/opencv/wiki/How_to_contribute

**Comment by ganler** [comment]
...OpenCV的VideoCapture的设计是为了通用。这个封装是无法代替VideoCapture的，因为我在README里画得改进后的图（其实画得不是很准确），如果要只用2个线程就达到最佳的话，需要平衡CAMERA和ALGORITHM的时间（并行编程的负载平衡），而这个平衡只能手动调，需要根据自己的相机型号（主要是帧率）和算法耗时，将算法的部分程序（比如预处理）转移到CAMERA线程（假设ALGORITHM比CAMERA慢很多）。
如果将这个封装替换掉VideoCapture的话，结果就是用额外的线程，做了微乎其微的加速（也不排除减速的情况）。
正确的使用方式就是拿这个封装，根据自己业务情况，平衡两个线程的负载，这样的加速结果才会很好。
